#!/bin/zsh

if [[ $# -gt 1 ]]; then
    echo "Too many arguments!"
elif [[ $# == 1 ]]; then
    if [[ $1 != "ocproxy" ]] then
        echo "The only argument that can be provided is ocproxy"
    fi
    unset http_proxy
    unset https_proxy
    sudo openconnect --user=ekarapet_de --script-tun --script "~/ocproxy_bin -D 11080" london-twvpn.oraclevpn.com 
else
    unset http_proxy
    unset https_proxy
    sudo openconnect --user=ekarapet_de london-twvpn.oraclevpn.com 
fi
